### ISSUE TITLE
GeoChart is empty

### ISSUE THREAD

**Issue by martinzbinden** [Perlkonig/grav-plugin-google-charts#1]
Tried to make a simple GeoChart in Grav. Unfortunately, just an empty map is displayed, no markers.

[gchart type=geochart id=test]{
    "data": [
        ["City",   "Graswachstum", "Woche"],
        ["Langenthal",      35,    12],
        ["Zollikofen",     25,    13]
    ],
    "options": {
        "region": "CH",
        "displayMode": "markers"
    }
}[/gchart]       

I think, I got something wrong. Anyone can help me?

**Comment by Perlkonig** [comment]
I apologize, Martin. Somehow I didn't see this issue come through. I'm afraid this is beyond the scope of the plugin. You'll need to review the Google Charts documentation and make sure your syntax is correct.
