### ISSUE TITLE
the chart disappear after the first page refresh

### ISSUE THREAD

**Issue by jprobichaud** [Perlkonig/grav-plugin-google-charts#3]
We are trying this extension for our knowledge wiki because it has the nice feature of importing the data from a separate file.

Unfortunately, even with all the data inside the page itself, we have the issue that the graph only shows itself when you first load the page.  If you hit "refresh" the graph disapear (at least with chrome and firefox 61.0).  

For the graph to show up again, I have to clear all caches from the Grav admin plugin.

This is with the 1.4.6 version of Grav.

Any ideas?

**Comment by Perlkonig** [comment]
To my knowledge, the only thing you can do is disable caching for this page. That's what I had to do for the demo page. Honestly, though, I haven't had the time to dig too deep into this to see if there's something I can do on my end. I've just written it off as a Grav issue. 

I will do some reading this weekend to see if there's something I can do to fix this. Thanks for your patience.

**Comment by Perlkonig** [comment]
v1.1.0 released. Works in my test environment. Let me know if you still have trouble.
