### ISSUE TITLE
Timeline Chart Support (...pleeeease)

### ISSUE THREAD

**Issue by leycec** [Perlkonig/grav-plugin-google-charts#4]
I politely beg you to support [timeline charts](https://developers.google.com/chart/interactive/docs/gallery/timeline), because they are quite awesome – especially for Grav-based project and document management. That said, I acknowledge that your time is scarce and precious and possibly better spent binging season eight of *Game of Thrones.* <sup>there's no shame in it</sup>

Thanks for all the intrepid volunteerism, @Perlkonig. Also, that's a sweet username. Also, I'm a fellow Canuck currently nestled in cottage country (Ontario). *Go, go, Canadian open-source power!* :maple_leaf:

**Comment by Perlkonig** [comment]
Sorry, man, I wish I could! From what I can tell, the Timelines API requires actual date objects; you can't just pass in a serialized array like all those other types. I could create a separate plugin, though, that only supports the Timelines type. I'll see what I can do.

Long live the Dominion! 🍁

**Comment by Perlkonig** [comment]
Hold the phone. There may be a way...

**Comment by Perlkonig** [comment]
Ask and you shall receive, as they say 😄 Version 1.1.1 released. Demo page will be updated shortly. Thanks for making me dig a little!

**Comment by leycec** [comment]
**Brilliant!** Feature begging has succeeded beyond wildest expectations. Thanks a metric ton for the crazy-rapid turnaround. Your devotion to the cause has inspired me to address [my own shamefully outstanding GitHub issues](https://github.com/leycec/raiagent/issues/69)...

May the Spring shine upon all true patriots of the North! :sun_with_face:
